version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: university_ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    networks:
      - university_network
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: university_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
      - ./backend/utils/unique_values_prompt.json:/app/backend/utils/unique_values_prompt.json
    environment:
      - CASSANDRA_HOST=sunway.hep88.com
      - CASSANDRA_PORT=9042
      - CASSANDRA_USERNAME=planusertest
      - CASSANDRA_PASSWORD=Ic7cU8K965Zqx
      - CASSANDRA_KEYSPACE=subjectplanning
      - OLLAMA_HOST=ollama
      - OLLAMA_PORT=11434
      - LLAMA_MODEL=llama3.2:latest
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - API_DEBUG=true
      - PYTHONPATH=/app
    networks:
      - university_network
    depends_on:
      - ollama
      - model_init
    restart: unless-stopped
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: university_frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    networks:
      - university_network
    depends_on:
      - backend
    restart: unless-stopped

  model_init:
    build:
      context: .
      dockerfile: Dockerfile.model_init
    container_name: university_model_init
    networks:
      - university_network
    depends_on:
      - ollama
    environment:
      - OLLAMA_HOST=ollama
      - OLLAMA_PORT=11434
    restart: "no"

volumes:
  ollama_data:
    driver: local

networks:
  university_network:
    driver: bridge